[2023-12-06 19:16:05,838] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:04:12.410031+00:00 [queued]>
[2023-12-06 19:16:05,859] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:04:12.410031+00:00 [queued]>
[2023-12-06 19:16:05,860] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 19:16:05,861] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-12-06 19:16:05,862] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 19:16:05,899] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-06 19:04:12.410031+00:00
[2023-12-06 19:16:05,910] {standard_task_runner.py:52} INFO - Started process 1639 to run task
[2023-12-06 19:16:05,923] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'transformar_data', 'manual__2023-12-06T19:04:12.410031+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpq9taq709', '--error-file', '/tmp/tmpja8yz63r']
[2023-12-06 19:16:05,928] {standard_task_runner.py:80} INFO - Job 67: Subtask transformar_data
[2023-12-06 19:16:06,198] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:04:12.410031+00:00 [running]> on host 4357a10b93bd
[2023-12-06 19:16:06,277] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-06 19:16:06,349] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T19:04:12.410031+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T19:04:12.410031+00:00
[2023-12-06 19:16:06,352] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-06 19
[2023-12-06 19:16:06,352] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 103, in transformar_data
    fullpage_movie = pages[f'df_movie_{1}']
KeyError: 'df_movie_1'
[2023-12-06 19:16:06,367] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=transformar_data, execution_date=20231206T190412, start_date=20231206T191605, end_date=20231206T191606
[2023-12-06 19:16:06,398] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task transformar_data ('df_movie_1'; 1639)
[2023-12-06 19:16:06,418] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-06 19:16:06,490] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
