[2023-12-20T20:11:43.105+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:11:17.199142+00:00 [queued]>
[2023-12-20T20:11:43.115+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:11:17.199142+00:00 [queued]>
[2023-12-20T20:11:43.115+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-20T20:11:43.133+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): mensaje_carga_completada> on 2023-12-20 20:11:17.199142+00:00
[2023-12-20T20:11:43.140+0000] {standard_task_runner.py:60} INFO - Started process 106 to run task
[2023-12-20T20:11:43.144+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'mensaje_carga_completada', 'manual__2023-12-20T20:11:17.199142+00:00', '--job-id', '316', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpuk2ed3eb']
[2023-12-20T20:11:43.146+0000] {standard_task_runner.py:88} INFO - Job 316: Subtask mensaje_carga_completada
[2023-12-20T20:11:43.159+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-12-20T20:11:43.191+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:11:17.199142+00:00 [running]> on host de1b3d441485
[2023-12-20T20:11:43.278+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_redshift_docker_***' AIRFLOW_CTX_TASK_ID='mensaje_carga_completada' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T20:11:17.199142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-20T20:11:17.199142+00:00'
[2023-12-20T20:11:44.740+0000] {logging_mixin.py:188} INFO - 'ascii' codec can't encode character '\xe1' in position 73: ordinal not in range(128)
[2023-12-20T20:11:44.741+0000] {logging_mixin.py:188} INFO - Failure
[2023-12-20T20:11:44.741+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-20T20:11:44.749+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=ETL_redshift_docker_***, task_id=mensaje_carga_completada, execution_date=20231220T201117, start_date=20231220T201143, end_date=20231220T201144
[2023-12-20T20:11:44.802+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-20T20:11:44.820+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
