[2023-12-20T20:05:07.671+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:04:25.280060+00:00 [queued]>
[2023-12-20T20:05:07.690+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:04:25.280060+00:00 [queued]>
[2023-12-20T20:05:07.691+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-20T20:05:07.737+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): mensaje_carga_completada> on 2023-12-20 20:04:25.280060+00:00
[2023-12-20T20:05:07.750+0000] {standard_task_runner.py:60} INFO - Started process 2006 to run task
[2023-12-20T20:05:07.755+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'mensaje_carga_completada', 'manual__2023-12-20T20:04:25.280060+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmp3wda205x']
[2023-12-20T20:05:07.756+0000] {standard_task_runner.py:88} INFO - Job 309: Subtask mensaje_carga_completada
[2023-12-20T20:05:07.771+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-12-20T20:05:07.806+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:04:25.280060+00:00 [running]> on host de1b3d441485
[2023-12-20T20:05:07.889+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_redshift_docker_***' AIRFLOW_CTX_TASK_ID='mensaje_carga_completada' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T20:04:25.280060+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-20T20:04:25.280060+00:00'
[2023-12-20T20:05:09.417+0000] {logging_mixin.py:188} INFO - 'ascii' codec can't encode character '\xe1' in position 73: ordinal not in range(128)
[2023-12-20T20:05:09.417+0000] {logging_mixin.py:188} INFO - Failure
[2023-12-20T20:05:09.418+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-20T20:05:09.430+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=ETL_redshift_docker_***, task_id=mensaje_carga_completada, execution_date=20231220T200425, start_date=20231220T200507, end_date=20231220T200509
[2023-12-20T20:05:09.453+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-20T20:05:09.469+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
