[2023-12-06 21:17:56,697] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [queued]>
[2023-12-06 21:17:56,737] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [queued]>
[2023-12-06 21:17:56,766] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 21:17:56,772] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-12-06 21:17:56,776] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 21:17:56,850] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-06 19:36:56.875589+00:00
[2023-12-06 21:17:57,000] {standard_task_runner.py:52} INFO - Started process 194 to run task
[2023-12-06 21:17:57,035] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'transformar_data', 'manual__2023-12-06T19:36:56.875589+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpiw0yd5od', '--error-file', '/tmp/tmp_zzheqin']
[2023-12-06 21:17:57,040] {standard_task_runner.py:80} INFO - Job 95: Subtask transformar_data
[2023-12-06 21:17:57,402] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [running]> on host 4357a10b93bd
[2023-12-06 21:17:57,637] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-06 21:17:57,810] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T19:36:56.875589+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T19:36:56.875589+00:00
[2023-12-06 21:17:57,815] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-06 19
[2023-12-06 21:17:57,824] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 103, in transformar_data
    fullpage_movie = pages[f'df_movie_{1}']
KeyError: 'df_movie_1'
[2023-12-06 21:17:57,860] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=transformar_data, execution_date=20231206T193656, start_date=20231206T211756, end_date=20231206T211757
[2023-12-06 21:17:57,905] {standard_task_runner.py:97} ERROR - Failed to execute job 95 for task transformar_data ('df_movie_1'; 194)
[2023-12-06 21:17:57,943] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-06 21:17:58,055] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
